### ISSUE TITLE
Next step

### ISSUE THREAD

**Issue by HydrogenC** [HydrogenC/WOT-Launcher#1]
Store the additional mods in an independent array. It needs a parameter called parent-node (IndependenceMod.Node). Add it to its parent-node while initialization. And these two arrays should be operated repetitively.

**Comment by HydrogenXYC** [comment]
The parent-node parameter should be its parent mod dot node.

**Comment by HydrogenXYC** [comment]
And disable checkboxes if file doesn’t exist.

**Comment by ChlorineX** [comment]
fixed in 83455fa
