### ISSUE TITLE
Function of apply changes need to be optimized! 

### ISSUE THREAD

**Issue by UraniumH** [HydrogenC/WOT-Launcher#3]
We should create a list to mark (or store) mods for additional and a list for deletions. It will improve the proformance a lot. See ceb32e2.

**Comment by HydrogenC** [comment]
I don't think it will work.

**Comment by HydrogenC** [comment]
I tried three times and it doesn’t work. Think of extending instead of inheriting.

**Comment by ChlorineX** [comment]
I said twice it won’t work! Listen to my words!

**Comment by UraniumH** [comment]
I know but this is truly a problem that needs to be solved. It will make great influence on the capacity. What’s more, this is even the base for many other functions.

**Comment by ChlorineX** [comment]
Don’t waste time on these useless functions. I eat sh*t if you finish this function!

**Comment by UraniumH** [comment]
Okay you are going to eat sh*t.

**Comment by UraniumH** [comment]
This is really very important!

**Comment by UraniumH** [comment]
Complete it anyway.

**Comment by HydrogenC** [comment]
Guys talk POLITELY!

**Comment by HydrogenC** [comment]
I agree with @ChlorineX. But we just need to finish it in a different way.

**Comment by ChlorineX** [comment]
Okay listen to the group leader @HydrogenC.

**Comment by HydrogenC** [comment]
It must be solved TOMORROW! We’ll get our first release tomorrow evening.

**Comment by ChlorineX** [comment]
Fine

**Comment by ChlorineX** [comment]
I won’t be able to participate because I know nothing about it!

**Comment by HydrogenC** [comment]
All right. @ChlorineX and I will finish the job.

**Comment by UraniumH** [comment]
But I don’t know any other methods to solve ：(

**Comment by HydrogenC** [comment]
Ahhh. Fine. I’ve solve it all by myself.

**Comment by UraniumH** [comment]
Can I close this issue then

**Comment by HydrogenC** [comment]
Sure

**Comment by HydrogenC** [comment]
Don’t forget to reference the commit to this issue @UraniumH

**Comment by UraniumH** [comment]
I’ll test the code in Test.cs tomorrow.

**Comment by UraniumH** [comment]
Do not close this issue until it has been solved.

**Comment by UraniumH** [comment]
IT truly works this time, but no use.
