### ISSUE TITLE
New issue?

### ISSUE THREAD

**Issue by UraniumH** [HydrogenC/WOT-Launcher#4]
It will only check one file to decide the multifile mod is installed or not. Suppose there is an half installed mod, the program will have an exception.

**Comment by HydrogenC** [comment]
Well, it used to check all files, but it affects too much to the capacity, so we have bd4463c2. However, this launcher is designed to work in the environment with no artificial changes. As these reasons, we probably won’t solve this.....

**Comment by UraniumH** [comment]
I see
